"""upgrade airport_id

Revision ID: 18485b6c921d
Revises: 8676d16f2525
Create Date: 2026-03-29 13:07:31.645518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18485b6c921d'
down_revision: Union[str, Sequence[str], None] = '8676d16f2525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('airports', 'airport_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_airports_id'), table_name='airports')
    op.drop_column('airports', 'id')

    op.create_primary_key(
    "pk_airports",
    "airports",
    ["airport_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airports', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_airports_id'), 'airports', ['id'], unique=False)
    op.alter_column('airports', 'airport_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
