"""add_is_first_login

Revision ID: 27dcac9bb310
Revises: 08124ed92556
Create Date: 2026-05-08 08:09:21.782265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27dcac9bb310'
down_revision: Union[str, Sequence[str], None] = '08124ed92556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_first_login', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_first_login')
    # ### end Alembic commands ###
