"""add certification

Revision ID: 769455f0b3e0
Revises: b3510b564ce5
Create Date: 2026-04-04 23:38:29.270989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769455f0b3e0'
down_revision: Union[str, Sequence[str], None] = 'b3510b564ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('users', sa.Column('certification_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'certifications', ['certification_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'certification_id')
    op.drop_table('certifications')
    # ### end Alembic commands ###
