"""add runway360

Revision ID: 8384d4e68b97
Revises: 2e63b4769efe
Create Date: 2026-03-30 22:26:22.006294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8384d4e68b97'
down_revision: Union[str, Sequence[str], None] = '2e63b4769efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runways',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airport_ident', sa.String(), nullable=True),
    sa.Column('le_ident', sa.String(), nullable=True),
    sa.Column('he_ident', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runways_airport_ident'), 'runways', ['airport_ident'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runways_airport_ident'), table_name='runways')
    op.drop_table('runways')
    # ### end Alembic commands ###
