"""add airport table

Revision ID: 8676d16f2525
Revises: e18c4dd4e988
Create Date: 2026-03-27 17:26:59.185647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8676d16f2525'
down_revision: Union[str, Sequence[str], None] = 'e18c4dd4e988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airport_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('towered_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airports_airport_id'), 'airports', ['airport_id'], unique=False)
    op.create_index(op.f('ix_airports_city'), 'airports', ['city'], unique=False)
    op.create_index(op.f('ix_airports_id'), 'airports', ['id'], unique=False)
    op.create_index(op.f('ix_airports_state'), 'airports', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airports_state'), table_name='airports')
    op.drop_index(op.f('ix_airports_id'), table_name='airports')
    op.drop_index(op.f('ix_airports_city'), table_name='airports')
    op.drop_index(op.f('ix_airports_airport_id'), table_name='airports')
    op.drop_table('airports')
    # ### end Alembic commands ###
