"""user certifications many to many

Revision ID: 9ebcd720b4d9
Revises: 769455f0b3e0
Create Date: 2026-04-05 00:14:58.502389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ebcd720b4d9'
down_revision: Union[str, Sequence[str], None] = '769455f0b3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_certifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('certification_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'certification_id')
    )
    op.drop_constraint(op.f('users_certification_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'certification_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('certification_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_certification_id_fkey'), 'users', 'certifications', ['certification_id'], ['id'])
    op.drop_table('user_certifications')
    # ### end Alembic commands ###
