"""user otp

Revision ID: a41c07f64ca6
Revises: 9ebcd720b4d9
Create Date: 2026-04-13 22:07:28.768083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41c07f64ca6'
down_revision: Union[str, Sequence[str], None] = '9ebcd720b4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_otp_expire', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reset_otp_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_otp_attempts')
    op.drop_column('users', 'reset_otp_expire')
    op.drop_column('users', 'reset_otp')
    # ### end Alembic commands ###
