"""add runway_heading

Revision ID: b3510b564ce5
Revises: c8e9e82aa70d
Create Date: 2026-04-04 16:47:22.078717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3510b564ce5'
down_revision: Union[str, Sequence[str], None] = 'c8e9e82aa70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runway_landings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('airport_id', sa.String(), nullable=False),
    sa.Column('runway_heading', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('aircraft', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.airport_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'runway_heading', name='uq_user_runway_heading')
    )
    op.create_index('idx_user_heading', 'runway_landings', ['user_id', 'runway_heading'], unique=False)
    op.create_index(op.f('ix_runway_landings_airport_id'), 'runway_landings', ['airport_id'], unique=False)
    op.create_index(op.f('ix_runway_landings_user_id'), 'runway_landings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runway_landings_user_id'), table_name='runway_landings')
    op.drop_index(op.f('ix_runway_landings_airport_id'), table_name='runway_landings')
    op.drop_index('idx_user_heading', table_name='runway_landings')
    op.drop_table('runway_landings')
    # ### end Alembic commands ###
