CLASS_B_AIRPORTS = [
    "KATL","KBOS","KBWI","KCLE","KCLT","KCVG","KDEN","KDFW",
    "KDTW","KEWR","KHOU","KIAH","KJFK","KLAS","KLAX","KLGA",
    "KMCI","KMCO","KMDW","KMEM","KMIA","KMSP","KMSY","KORD",
    "KPHL","KPHX","KPIT","KSAN","KSEA","KSFO","KSLC","KSTL","KTPA"
]